<?php
include_once('statuscode.php');
include_once('http_response_message.php');
class http_response
{
	
	private static $response_text;
	private static $response_status;
	public static $print_response = true;

	public function getResponseText(){
		return self::$response_text;
	}

	public function setResponseText($text){
		self::$response_text = $text;
	}

	public function getResponseStatus(){
		return self::$response_status;
	}

	public function setResponseStatus($response_status){
		self::$response_status = $response_status;
	}

	/*
	$response - SUCCESS / ERROR / WARNING
	$response_code - the code is available in parent class http_response_code
	$status_code - which is http status code for created, bad request and so on...
	$data - send this data back to client side
	$msg - this msg is generated by try catch block
	*/
	function generate($response, $response_code = NULL, $status_code, $data=array(), $msg = NULL){
		StatusCode::http_response_code($status_code);
		$response_array['status'] = $response;
		$response_array['message'] = (($msg != NULL) ? $msg : http_response_message::$response_message[$response_code]);
		if(is_array($data) && sizeof($data) > 0){
			$response_array['data'] = $data;
		}
		
		self::setResponseStatus($response);
		self::setResponseText(json_encode($response_array));

		if($msg != NULL){
			errorlog::save('Caught exception: '.  $msg);
		}
		
		if(self::$print_response) {
			echo self::getResponseText();
			exit;
		}
	}
}
